version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      POSTGRES_USER: duke
      POSTGRES_PASSWORD: 1234
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: personal-cars

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'

#  docker run --name java-postgres -p 5432:5432 -e POSTGRES_USER=duke -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=personal-cars -d postgres:15
